id: I84890981
legacy_id: null
ocr_import_info:
  bdrc_scan_id: W3CN7845
  source: bdrc
  ocr_info:
    timestamp: '2023-02-01T00:00:00Z'
  batch_id: batch-0002
  software_id: norbuketaka
  expected_default_language: bo
  op_import_options: null
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2023-12-16T17:20:52.011733'
last_modified: '2023-02-01T00:00:00+00:00'
parser: https://github.com/OpenPecha/Norbu-Keta-eText-import/blob/main/norbu_ketaka_parser.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN7845
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN7845
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བླ་མེད་རྡོ་རྗེ་ཐེག་པའི་ལམ་གྱི་སྔོན་འགྲོ་སོགས།
  languages:
  - bo
  author: ངོར་མཁན་ཆེན ༠༢་དཀོན་མཆོག་རྒྱལ་མཚན།
statistics: null
quality: null
bases:
  I3CN7847:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7847
      total_pages: 426
      volume_number: 1
      volume_pages_bdrc_intro: 2
    base_file: I3CN7847.txt
    order: 1
  I3CN7848:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7848
      total_pages: 438
      volume_number: 2
      volume_pages_bdrc_intro: 2
    base_file: I3CN7848.txt
    order: 2
  I3CN7849:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7849
      total_pages: 506
      volume_number: 3
      volume_pages_bdrc_intro: 2
    base_file: I3CN7849.txt
    order: 3
copyright:
  status: Public domain
  notice: The proofread texts are donated by the Norbu Ketaka project led by Queenie
    Luo (Harvard University), Zhiying Li (Sichuan University) and Leonard van der
    Kuijp (Harvard University). Correspondence should be directed to  queenieluo@g.harvard.edu
  info_url: null
license: CC0
